// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace sample
{
	public partial class CustomPageViewController : UIViewController
	{
		public CustomPageViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
